/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as antAgingPillsSol from "./AntAgingPills.sol";
export type { antAgingPillsSol };
import type * as basicNftSol from "./BasicNft.sol";
export type { basicNftSol };
export type { MockERC20 } from "./MockERC20";
