/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AntAgingPills__factory } from "./AntAgingPills__factory";
export { BasicNft__factory } from "./BasicNft__factory";
