/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as antAgingPillsSol from "./AntAgingPills.sol";
export * as basicNftSol from "./BasicNft.sol";
export { MockERC20__factory } from "./MockERC20__factory";
